server:
  port: 8081
feign:
  client:
    config:
      producer:
        connectTimeout: 5000
        readTimeout: 3000
ribbon:
  eager-load:
    enabled: true

producer:
  ribbon:
    listOfServices: http://localhost:8082, http://localhost:8083

persistence-ribbon:
  enable: true