server:
  port: 8081
feign:
  client:
    config:
      producer:
        connectTimeout: 5000
        readTimeout: 3000
ribbon:
  eager-load:
    enabled: true
debug: true
persistence-ribbon:
  enable: false
producer:
  ribbon:
    NFLoadBalancerRuleClassName: com.jay.ribbon.PersistenceRule
